# Generated by Django 5.2.7 on 2025-12-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_avaliacao_nome_completo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data', '-hora'], 'verbose_name': 'Avaliação Física', 'verbose_name_plural': 'Avaliações Físicas'},
        ),
        migrations.AlterModelOptions(
            name='campo',
            options={'ordering': ['nome'], 'verbose_name': 'Campo', 'verbose_name_plural': 'Campos'},
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['nome'], 'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterModelOptions(
            name='trainingexercicio',
            options={'ordering': ['-id'], 'verbose_name': 'Programa de Treinamento', 'verbose_name_plural': 'Programas de Treinamento'},
        ),
    ]
