# Generated by Django 5.2.7 on 2025-12-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_alter_avaliacao_options_alter_campo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercicio',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Vídeo'),
        ),
    ]
