# Generated by Django 5.2.7 on 2025-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_problemamedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='MATRICULA'),
        ),
    ]
