# Generated by Django 5.2.7 on 2025-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_add_unique_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=14, unique=True, verbose_name='MATRICULA')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('utilizada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Matrícula Disponível',
                'verbose_name_plural': 'Matrículas Disponíveis',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
