# Generated by Django 5.2.7 on 2025-12-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_matriculadisponivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imcregistro',
            options={'ordering': ['-data_registro'], 'verbose_name': 'Registro de IMC', 'verbose_name_plural': 'Registros de IMC'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='problemamedico',
            options={'ordering': ['-data_registro'], 'verbose_name': 'Problema Médico', 'verbose_name_plural': 'Problemas Médicos'},
        ),
    ]
